- name: Test whether node exists
  command: "test -f /usr/local/bin/node"
  register: node_exists
  ignore_errors: True

- name: Install nodejs {{node_version}}
  get_url: url=http://nodejs.org/dist/v{{node_version}}/node-v{{node_version}}-linux-x64.tar.gz dest=/tmp/node-v{{node_version}}-linux-x64.tar.gz
  register: download
  when: node_exists.rc == 1

- name: unarchive nodejs
  become: yes
  shell: "tar --strip-components 1 -xzvf /tmp/node-v* -C /usr/local"
  when: download|success
  register: unarchived
